image: python:3.8

stages:
  - tutorials

variables:
  PYTHON_VERSION: "3.8"

before_script:
  - python -m pip install --upgrade pip
  - python setup.py install

test:
  stage: tutorials
  script:
    - python -m unittest discover -s tutorials -p "*.py"
